//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClansHuntApp.Infrastructure.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberStatusEntity
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public int DonationsGiven { get; set; }
        public int DonationsReceived { get; set; }
        public System.DateTime StatusDate { get; set; }
    
        public virtual MemberEntity Member { get; set; }
    }
}
