//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClansHuntApp.Infrastructure.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberEntity()
        {
            this.MemberStatus = new HashSet<MemberStatusEntity>();
        }
    
        public int ID { get; set; }
        public string Tag { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberStatusEntity> MemberStatus { get; set; }
    }
}
